<?php
// This file generated by Propel convert-props target on Thu Feb 21 18:54:32 2008
// from XML runtime conf file /home/mward/library/./runtime-conf.xml
return array (
  'log' => 
  array (
    'type' => 'file',
    'name' => '/home/mward/library/logs/propel.log',
    'ident' => 'library',
    'level' => '7',
  ),
  'propel' => 
  array (
    'datasources' => 
    array (
      'library' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'phptype' => 'mysql',
          'database' => 'library',
          'hostspec' => 'localhost',
          'username' => 'library',
          'password' => 'Mei8onoo',
        ),
      ),
      'default' => 'library',
    ),
  ),
);